// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDZw4VTSrK6982xNoqhARac2L2iWRNgkU',
    appId: '1:156330108797:web:3d0bce0b6a9ad273560e14',
    messagingSenderId: '156330108797',
    projectId: 'todo-10df7',
    authDomain: 'todo-10df7.firebaseapp.com',
    storageBucket: 'todo-10df7.appspot.com',
    measurementId: 'G-08TPHXY4FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiF80p1h6pE_X9ZLnTnmnSuIq8244MUE0',
    appId: '1:156330108797:android:2da2f28b50ae98df560e14',
    messagingSenderId: '156330108797',
    projectId: 'todo-10df7',
    storageBucket: 'todo-10df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ9hBQO7zCwhNAtMjQkV7iOjqfaJ7L9Y8',
    appId: '1:156330108797:ios:9e1541c091e58c00560e14',
    messagingSenderId: '156330108797',
    projectId: 'todo-10df7',
    storageBucket: 'todo-10df7.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ9hBQO7zCwhNAtMjQkV7iOjqfaJ7L9Y8',
    appId: '1:156330108797:ios:9e1541c091e58c00560e14',
    messagingSenderId: '156330108797',
    projectId: 'todo-10df7',
    storageBucket: 'todo-10df7.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDZw4VTSrK6982xNoqhARac2L2iWRNgkU',
    appId: '1:156330108797:web:6396737b42db4d17560e14',
    messagingSenderId: '156330108797',
    projectId: 'todo-10df7',
    authDomain: 'todo-10df7.firebaseapp.com',
    storageBucket: 'todo-10df7.appspot.com',
    measurementId: 'G-FQWNGWWJDC',
  );

}